blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/DiscordAnalytics/mongo-backups-manager/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Questions or Support
    url: https://github.com/DiscordAnalytics/mongo-backups-manager/discussions/new?category=q-a
    about: Ask the community for help